name: khronic-pain

description: pain forever

base-image: quay.io/fedora-ostree-desktops/silverblue
image-version: 42

modules:
  - from-file: packages.yml
  - from-file: files.yml
  - from-file: services.yml
  - type: signing  